[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ziya-celebi", email = "ziyacelebi30@gmail.com" },
    { name = "smile-core", email = "smileshalom74@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cloudinary>=1.36.0",
    "fastapi>=0.141.1",
    "google-genai>=1.0.0",
    "jinja2>=3.1.6",
    "mangum>=0.17.0",
    "psycopg2-binary>=2.9.9",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[dependency-groups]
dev = [
    "httpx2>=2.12.0",
    "pytest>=8",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
